name: Build & Publish Picks

permissions:
  contents: write

on:
  schedule:
    - cron: '0 3 * * *'   # change as needed (UTC)
  workflow_dispatch: {}

concurrency:
  group: daily-picks
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Dublin
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i --no-audit --no-fund; fi

      - name: Install Playwright browsers (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Scrape racecards
        run: npm run scrape

      - name: Analyze with Perplexity
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        run: npm run analyze

      - name: Postbuild (copy latest to docs/latest.json)
        run: npm run postbuild

      - name: Archive daily + rebuild index
        run: npm run archive

      - name: Commit updated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/latest.json
          git add betfair-racecards-picks-*.json || true
          git commit -m "Update picks" || echo "No changes"
          git push
